### ISSUE TITLE
Language Code of Chinese family

### ISSUE THREAD

**Issue by Max-Sum** [blueset/efb-telegram-master#12]
According to the newest standard, the language code scheme should be:
[Macro Language]-[Language]-[Script]-[Region Varient].
For example:
Mandarin written in Simplifed Chinese of mainland China: zh-cmn-Hans-CN
Mandarin written in Traditional Chinese of Hong Kong: zh-cmn-Hant-HK
Cantonese written in Simplifed Chinese of Taiwan: zh-yue-Hans-TW
Hakka language written in Simplifed Chinese of mainland China: zh-hak-Hans-CN

Parts can be ignore in case the information is not important.

In the case of speed recognition, we want to focus on the oral language, so we should use:
(zh-)cmn, (zh-)yue to represent Mandarin and Cantonese. If we want to control the output script used to write the language, script code(Hans, Hant) should also be added.

PS: at least, we should use yue instead of ct as the code for cantonese.

**Comment by blueset** [comment]
Language code is used in multiple components in this project. 

## Localization
The localization part of this project is using GNU's `gettext`, which is taking the `lanugage_COUNTRY` code standard (ISO 639, ISO 3166, both in the 2 letters standard)
This is decided by the `gettext` library and we can not change it.

## Telegram user language detection
Telegram is offering a non-standard IETF language code to indicate the language used by the Telegram user. ETM uses this information to change ETM's display language dynamically. We used a Python library to convert IETF language code to `gettext`'s language code for compatibility purpose.

## Speech recognition
Currently Bing and Baidu's speech recognition API is implemented in ETM. The language codes used is directly from their corresponding API specifications, id est, we are using the language code format or standard that their API specifications require. We prefer not to make changes to it, so as to follow their standard directly.

----

As per your description, the standard you are talking about is the IETF language code standard. I personally prefer this one as well, but we have decided to follow the existing plan due to the reason above.

Hope this answers your question.
