### ISSUE TITLE
link become invalid caused by the changing of ID in chat list of wechat

### ISSUE THREAD

**Issue by jemyzhang** [blueset/efb-telegram-master#13]
The chat id of wechat will be changed sometimes, and the link to the tg group will become invalid.

When will the chat id be changed?
And is there any way to automatically update the chat id to the sqlite database?

**Comment by jemyzhang** [comment]
I've create a scripts for updating the database by compare with the chat list.

<script src="https://gist.github.com/jemyzhang/c56fbbda0b9c5707ecb254f398bf3bf5.js"></script>

with the command: `0_get_chat_list` we can get the chat list, if you got the old chat list backup, then things become easy.

**Comment by blueset** [comment]
This is an known issue in EWS, and due to the limited information offered from Web WeChat, detail of which is introduced in EWS's README file. We try to minimise the unexpected change of pseudo chat ID as far as possible using `wxpy`'s library. However, it is not fully prevented. 

If you want to follow up this issue, please open a new issue at EWS's repository as this is not relavent to ETM.
