### ISSUE TITLE
Database (msglog.pickle) size inflation issue

### ISSUE THREAD

**Issue by jemyzhang** [blueset/efb-telegram-master#79]
Is the msglog necessary saving forever? I think all of the messages are already keeping inside telegram chat logs. Any idea to cleanup the extraordinary large table which is increasing day by day?

**Comment by blueset** [comment]
The `msglog` table of the database stores metadata of all past messages in order to:
- enable quoted replies
- allow message edits, deletes and reactions
- associate message ID on Telegram with that from slave channels
- allow middlewares to retrieve attachment files for further processing.

In the latest version, each message should take about 1 kB of size on average, and we are trying to work towards a lower space consumption.

If you think some older messages might not be used anymore, you can select all older message with the `time` column, and delete them using an SQLite client of your choice.

**Comment by blueset** [comment]
Note on pickle data compression:

I so far came out with 3 options to work on this.

1. Abandon SQLite and use another database system that supports inter-row blob compression. This could introduce additional setup cost on the users.
2. Switch to a different serialization protocol that supports built-in schema (maybe ProtoBuf?). This would make old entries incompatible and changing schema afterwards can be difficult.
3. Give up on pickling and map each attribute of message/chat object to a database field. Storage-effecient conversion code could be hard to write and maintain, and database schema is hard to change either.

**Comment by blueset** [comment]
Note: Some serialization protocols found with schemas built-in.
- [Cap'n proto](https://capnproto.org/otherlang.html)
- [Apache Arvo](http://avro.apache.org/docs/current/gettingstartedpython.html)
- [ProtoBuf](https://developers.google.com/protocol-buffers/docs/pythontutorial)

**Comment by blueset** [comment]
Since ETM 2.0.0b34, another measure is taken to minimize `pickle` field in `msglog` table — reuse existing fields in the table and only pickle other additional (rarely used) attributes to the table.

I will keep this issue open for a while to see the effect of this measure. If there'll be no further report on overly large database size after a while, I will close the issue by then.
